import Head from "next/head";
import Footer from "@/Components/Footer";
import Header from "@/Components/Header";
import Navigation from "@/Components/Navigation";
import Grid from "@/Components/Grid";
import styles from "@/styles/Home.module.css";
import { useState } from "react";




export default function Home() {

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navigation/>
    


      <main className={`${styles.main}`}>
      <Grid/>
    


      </main>
      <footer>
        <Footer/>
      </footer>
    </>
  );
}
